set encoding=utf-8
set number
set wrap 
set mouse=a
set wildmenu
set lazyredraw
set showmatch
set ruler
set belloff=all
set tabstop=4
set autoindent
set smartindent
set incsearch
set hlsearch
set t_Co=256
set termguicolors
syntax enable
colorscheme catppuccin_mocha
